// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqzmt_G_L3-k-lG__l2IVKiXBsUY5Oxg',
    appId: '1:177021912731:web:1272389f12d3ece683283e',
    messagingSenderId: '177021912731',
    projectId: 'teste-74f08',
    authDomain: 'teste-74f08.firebaseapp.com',
    storageBucket: 'teste-74f08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDY37LdQx5WdXHn-xnH-z4FRkqqCzRw1w',
    appId: '1:177021912731:android:e42de0c39ebb7da183283e',
    messagingSenderId: '177021912731',
    projectId: 'teste-74f08',
    storageBucket: 'teste-74f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl4Rk7DvS2lL0hRiMcjF7WnbYP_0h8LQI',
    appId: '1:177021912731:ios:f527ea7cfc3c788f83283e',
    messagingSenderId: '177021912731',
    projectId: 'teste-74f08',
    storageBucket: 'teste-74f08.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl4Rk7DvS2lL0hRiMcjF7WnbYP_0h8LQI',
    appId: '1:177021912731:ios:f13eb6147487b84583283e',
    messagingSenderId: '177021912731',
    projectId: 'teste-74f08',
    storageBucket: 'teste-74f08.appspot.com',
    iosBundleId: 'com.example.teste.RunnerTests',
  );
}
